### ISSUE TITLE
Date Picker flickering 

### ISSUE THREAD

**Issue by anuragsgupta** [DJ-Raven/flatlaf-dashboard-pro#2]
https://github.com/DJ-Raven/flatlaf-dashboard-pro/assets/82273319/d6115423-338a-47fb-bd3b-6eb582803346

whenever try use date picker, this flickering problem occurs, I have tried with different version of java same error, i am using date chooser swing jar 1.4.1 made by you.

**Comment by DJ-Raven** [comment]
@anuragsgupta Can you run my test file that I have push [here](https://github.com/DJ-Raven/flatlaf-dashboard-pro/tree/main/test/test) to make sure this date chooser no error with this dashboard form.
I already test with my pc it's work well, pls clone new project and test. thank

**Comment by anuragsgupta** [comment]
https://github.com/DJ-Raven/flatlaf-dashboard-pro/assets/82273319/02c4b0ca-2391-49a3-85ed-4bc3ae723fac

It works fine on Linux OS, but I suspect there's an issue with my Windows. Do you know why this might be happening and how I can fix it? Sometimes it starts working automatically.
